### PR TITLE
Fix build with Cabal-2.2.0.x

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
Still getting failures with `ghc-mod check`:

```
/home/hasufell/.cache/cabal-helper/cabal-helper0.8.0.3-Cabal2.2.0.1.build/CabalHelper/Runtime/Main.hs:314:34: error:
    • Couldn't match expected type ‘[(FlagName, Bool)]’
                  with actual type ‘FlagAssignment’
    • In the second argument of ‘($)’, namely
        ‘configConfigurationsFlags $ configFlags lbi’
      In the second argument of ‘($)’, namely
        ‘map (first unFlagName)
         $ configConfigurationsFlags $ configFlags lbi’
      In the second argument of ‘($)’, namely
        ‘sort
         $ map (first unFlagName)
           $ configConfigurationsFlags $ configFlags lbi’

/home/hasufell/.cache/cabal-helper/cabal-helper0.8.0.3-Cabal2.2.0.1.build/CabalHelper/Runtime/Main.hs:322:51: error:
    • Couldn't match expected type ‘[(FlagName, Bool)]’
                  with actual type ‘FlagAssignment’
    • In the expression: flagAssgnments
      In a stmt of a list comprehension:
        (unFlagName -> flag_name, val) <- flagAssgnments
      In the expression:
        [(flag_name, val) |
           MkFlag {flagName = (unFlagName -> flag_name'),
                   flagDefault = def_val} <- flagDefinitons,
           (unFlagName -> flag_name, val) <- flagAssgnments,
           flag_name == flag_name',
           val /= def_val]
```

File: cabal-helper.cabal [hunk 1]
```diff
@@ -1,5 +1,5 @@
 name:                cabal-helper
-version:             0.8.0.2
+version:             0.8.0.3
```
Comment (DanielG) [inline cabal-helper.cabal:2]: I think we ought to at least do a minor version bump for new Cabal version support. I'd actually prefer to bump the version myself since its part of the release process if you don't mind.

File: src/CabalHelper/Runtime/Main.hs [hunk 2]
```diff
@@ -195,6 +192,13 @@ import Distribution.Version
 import qualified Distribution.InstalledPackageInfo as Installed
 #endif
 
+#if CH_MIN_VERSION_Cabal(2,2,0)
+import Distribution.Types.GenericPackageDescription
+  (
+    unFlagAssignment
+  )
```
Comment (DanielG) [inline src/CabalHelper/Runtime/Main.hs:199]: Please keep to the surrounding code style.

**Review by DanielG — CHANGES_REQUESTED** [review]
Thanks for the PR! I've added you to the collaborators list, if you push the updated PR into a branch in this repo it will be built by the CI system. (GitLab CI unfortunately doesn't support building Github PRs yet)

**Comment by hasufell** [comment]
Reopened here: https://github.com/DanielG/cabal-helper/pull/53
